// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwhzqowhrpclguvtsisb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3aHpxb3docnBjbGd1dnRzaXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMjIxNDAsImV4cCI6MjA1NDU5ODE0MH0.ws9jT7ptUKn1n8conoS9K4TDn5dEibGkyIl1V0t9LGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);